console.log('Hello  friend!')
console.log('This is package A.')
console.log('Add feature 2')
console.log('Add feature 3')
console.log('Add feature 4')
console.log('Add feature 6')
console.log('Add feature 5')
