console.log('Hello friend!');
console.log('This is package B.');
console.log('Add feature 2');
console.log('Add feature 3');
console.log('Add feature 4');
console.log('Add feature 5');
console.log('Add feature 6');
console.log('Add feature 7');
console.log('Add feature 8');
console.log('Add feature 9');
console.log('Add feature 11');
console.log('Add feature 12');
console.log('Add feature 13');
console.log('Add feature 14');
console.log('Add feature 15');
console.log('Add feature 16');
console.log('Add feature 17');
console.log('Add feature 18');
console.log('Add feature 19');
console.log('Add feature 20');
console.log('Add feature 21');
console.log('Add feature 22');
console.log('Add feature 23');
console.log('Add feature 24');