name: default
on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo${{ github.event_name }} ${{ github.event.pull_request.labels.*.name }}
      - name: Skip on release
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'release')
        run: exit 78
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0