name: feature
on:
  pull_request_target:
    branches:
      - 'main'
    paths:
      - '**main.js'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Skip on release
        run: exit 0