name: release-pr
on:
  pull_request_target:
    branches:
      - 'main'
    paths:
      - '**CHANGELOG.md'

jobs:
  release-build:
    name: release-build
    runs-on: ubuntu-latest
    steps:
      - name: Skip on release
        run: exit 0